apiVersion: v1
kind: Service
metadata:
  name: service-snowflake-clusterip
spec:
  type: ClusterIP
  selector:
    app: snowflake
  ports:
    - port: 7020
      targetPort: 7020

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      containers:
        - image: guptang/tiktok-snowflake:v1
          name: tiktok-snowflake-container